import json
from string import punctuation
from urlparse import urlparse
from django.core.files import File


def cleanTweet(tweet_text):
    '''
    clean the tweeets from the incoming stream of data
    :param tweet_text:
    :return:
    '''
    pt = tweet_text.lower()
    processedTweet = ''

    for i in pt.split():
        s, n, p, pa, q, f = urlparse(i)
        if s and n:
            pass
        elif i[:1] == '@':
            pass
        elif i[:1] == '#':
            processedTweet = processedTweet.strip() + ' ' + i[1:]
        else:
            processedTweet = processedTweet.strip() + ' ' + i

    for i in list(punctuation):
        processedTweet = processedTweet.replace(i, '')

    return processedTweet


def sentiment_list():
    '''
    open up the wordlist contianing the positive and negative words to calculate the sentiments.
    :return:
    '''
    scores = {'limited': -1.0, 'suicidal': -2.0, 'pardon': 2.0, 'desirable': 2.0, 'protest': -2.0,
                 'lurking': -1.0, u'controversial': -2.0, u'hating': -3.0, u'ridiculous': -3.0, u'hate': -3.0,
                 'aggression': -2.0, u'increase': 1.0, u'regretted': -2.0, u'violate': -2.0, u'granting': 1.0,
                 'attracted': 1.0, u'poorest': -2.0, u'scold': -2.0, u'bailout': -2.0, u'sorry': -1.0,
                 'regrets': -2.0, u'struck': -1.0, u'misreporting': -2.0, u'vociferous': -1.0, u'lurk': -1.0,
                 'misunderstanding': -2.0, u'distort': -2.0, u'stolen': -2.0, u'gratification': 2.0,
                 'uncertain': -1.0, u'stabbed': -2.0, u'screaming': -2.0, u'courageous': 2.0, u'disturb': -2.0,
                 'exaggerate': -2.0, u'harried': -2.0, u'solution': 1.0, u'nigger': -5.0, u'pardons': 2.0,
                 'quaking': -2.0, u'monopolized': -2.0, u'censors': -2.0, u'triumph': 4.0, u'enjoy': 2.0,
                 'shithead': -4.0, u'tired': -2.0, u'warns': -2.0, u'landmark': 2.0, u'elegant': 2.0, u'fabulous': 4.0,
                 'rigorous': 3.0, u'emptiness': -1.0, u'loathing': -3.0, u'errors': -2.0, u'hide': -1.0,
                 'wreck': -2.0, u'desirous': 2.0, u'integrity': 2.0, u'beaten': -2.0, u'jocular': 2.0, u'poison': -2.0,
                 'victims': -3.0, u'endorse': 2.0, u'shocks': -2.0, u'unmotivated': -2.0, u'hero': 2.0, u'avert': -1.0,
                 'festive': 2.0, u'interrupting': -2.0, u'prblms': -2.0, u'active': 1.0, u'oversells': -2.0,
                 'kudos': 3.0, u'rigorously': 3.0, u'deferring': -1.0, u'postpones': -1.0, u'oxymoron': -1.0,
                 'launched': 1.0, u'stressed': -2.0, u'lonesome': -2.0, u'unwanted': -2.0, u'postponed': -1.0,
                 'missing': -2.0, u'criticism': -2.0, u'fantastic': 4.0, u'secure': 2.0, u'dehumanize': -2.0,
                 'cheats': -3.0, u'sparkling': 3.0, u'achievable': 1.0, u'cherishing': 2.0, u'criminals': -3.0,
                 'appeasing': 2.0, u'motivate': 1.0, u'negative': -2.0, u'insult': -2.0, u'calm': 2.0,
                 'recommend': 2.0, u'strike': -1.0, u'committing': 1.0, u'made-up': -1.0, u'supporters': 1.0,
                 'successful': 3.0, u'expose': -1.0, u'haha': 3.0, u'award': 3.0, u'hurt': -2.0, u'grief': -2.0,
                 'disruption': -2.0, u'sobering': 1.0, u'frenzy': -3.0, u'excellent': 3.0, u'blocking': -1.0,
                 'shoot': -1.0, u'disappointing': -2.0, u'join': 1.0, u'somber': -2.0, u'refusing': -2.0,
                 'worn': -1.0, u'worth': 2.0, u'lugubrious': -2.0, u'criticizing': -2.0, u'elegantly': 2.0,
                 'defer': -1.0, u'pollute': -2.0, u'joyous': 3.0, u'unjust': -2.0, u'laughs': 1.0, u'shattered': -2.0,
                 'want': 1.0, u'indifferent': -2.0, u'attract': 1.0, u'cocksucker': -5.0, u'guarantee': 1.0,
                 'farce': -1.0, u'anguish': -3.0, u'puzzled': -2.0, u'nuts': -3.0, u'damage': -3.0, u'amazing': 4.0,
                 'uncredited': -1.0, u'trusted': 2.0, u'aching': -2.0, u'significance': 1.0, u'moron': -3.0,
                 'disappoint': -2.0, u'bankster': -3.0, u'undesirable': -2.0, u'badly': -3.0, u'uselessness': -2.0,
                 'flustered': -2.0, u'mess': -2.0, u'insecure': -2.0, u'lag': -1.0, u'loyalty': 3.0,
                 'demanding': -1.0, u'astoundingly': 3.0, u'wrong': -2.0, u'sentencing': -2.0, u'sparkles': 3.0,
                 'meaningful': 2.0, u'ambivalent': -1.0, u'complacent': -2.0, u'splendid': 3.0, u'effective': 2.0,
                 'wins': 4.0, u'attracts': 1.0, u'appreciate': 2.0, u'greet': 1.0, u'stimulate': 1.0,
                 'daredevil': 2.0, u'steals': -2.0, u'worst': -3.0, u'greed': -3.0, u'restriction': -2.0,
                 'dirtiest': -2.0, u'consent': 2.0, u'derides': -2.0, u'rotfl': 4.0, u'innovative': 2.0,
                 'responsive': 2.0, u'derided': -2.0, u'cool stuff': 3.0, u'welcomes': 2.0, u'fit': 1.0,
                 'polluters': -2.0, u'destroyed': -3.0, u'affected': -1.0, u'litigious': -2.0, u'prevented': -1.0,
                 'powerful': 2.0, u'safe': 1.0, u'supporter': 1.0, u'collide': -1.0, u'avoids': -1.0,
                 'mongering': -2.0, u'interrupt': -2.0, u'soothing': 3.0, u'lenient': 1.0, u'saddened': -2.0,
                 'gloom': -1.0, u'brightness': 1.0, u'arrested': -3.0, u'absolve': 2.0, u'dumps': -1.0,
                 'misbehave': -2.0, u'fitness': 1.0, u'entitled': 1.0, u'vitriolic': -3.0, u'luck': 3.0,
                 'interruption': -2.0, u'exhilarated': 3.0, u'celebrating': 3.0, u'exhilarates': 3.0,
                 'substantially': 1.0, u'tricked': -2.0, u'absolves': 2.0, u'contend': -1.0, u'touts': -2.0,
                 'pesky': -2.0, u'god': 1.0, u'lurks': -1.0, u'sparkle': 3.0, u'encourage': 2.0, u'loathe': -3.0,
                 'heavenly': 4.0, u'ranter': -3.0, u'sluggish': -2.0, u'disputed': -2.0, u'barrier': -2.0,
                 'threatened': -2.0, u'revenge': -2.0, u'free': 1.0, u'mourning': -2.0, u'admits': -1.0,
                 'unconvinced': -1.0, u'fervid': 2.0, u'disputes': -2.0, u'struggle': -2.0, u'boosting': 1.0,
                 'enlightened': 2.0, u'jubilant': 3.0, u'exposing': -1.0, u'brooding': -2.0, u'tolerant': 2.0,
                 'disturbed': -2.0, u'hopeless': -2.0, u'ineffectively': -2.0, u'enraged': -2.0, u'wronged': -2.0,
                 'attractions': 2.0, u'reassure': 1.0, u'lovable': 3.0, u'rant': -3.0, u'downside': -2.0,
                 'enrages': -2.0, u'clarity': 2.0, u'snubbing': -2.0, u'dysfunction': -2.0, u'cheerless': -2.0,
                 'rejects': -1.0, u'lawsuits': -2.0, u'euphoric': 4.0, u'euphoria': 3.0, u'enthral': 3.0,
                 'combats': -1.0, u'tragic': -2.0, u'inconvenient': -2.0, u'bitter': -2.0, u'lunatics': -3.0,
                 'troubled': -2.0, u'murder': -2.0, u'collapse': -2.0, u'conciliated': 2.0, u'rejected': -1.0,
                 'conciliates': 2.0, u'wasted': -2.0, u'positively': 2.0, u'mercy': 2.0, u'anxiety': -2.0,
                 'coward': -2.0, u'matter': 1.0, u'guilt': -3.0, u'mirth': 3.0, u'feeling': 1.0, u'slashes': -2.0,
                 'self-confident': 2.0, u'willingness': 2.0, u'pessimism': -2.0, u'upset': -2.0, u'antagonistic': -2.0,
                 'enchanted': 2.0, u'unconcerned': -2.0, u'strengthening': 2.0, u'forced': -1.0, u'strength': 2.0,
                 'reassuring': 2.0, u'responsible': 2.0, u'isolated': -1.0, u'impotent': -2.0, u'elation': 3.0,
                 'recommended': 2.0, u'absorbed': 1.0, u'laughed': 1.0, u'enlightens': 2.0, u'yucky': -2.0,
                 'indoctrinate': -2.0, u'unsecured': -2.0, u'incapable': -2.0, u'distracts': -2.0, u'visionary': 3.0,
                 'vexing': -2.0, u'debonair': 2.0, u'disjointed': -2.0, u'relieving': 2.0, u'sulking': -2.0,
                 'exonerate': 2.0, u'treasonous': -3.0, u'stupid': -2.0, u'lifesaver': 4.0, u'alarm': -2.0,
                 'flop': -2.0, u'solemn': -1.0, u'demoralized': -2.0, u'unsophisticated': -2.0, u'entertaining': 2.0,
                 'annoyed': -2.0, u'marvel': 3.0, u'pardoned': 2.0, u'bomb': -1.0, u'inspire': 2.0, u'hunger': -2.0,
                 'rapture': 2.0, u'dupe': -2.0, u'disturbs': -2.0, u'solutions': 1.0, u'smog': -2.0, u'acquit': 2.0,
                 'unemployment': -2.0, u'contagions': -2.0, u'bliss': 3.0, u'disgust': -3.0, u'enslave': -2.0,
                 'adequate': 1.0, u'jailed': -2.0, u'explorations': 1.0, u'criticizes': -2.0, u'stop': -1.0,
                 'denounce': -2.0, u'unfair': -2.0, u'frowning': -1.0, u'haunted': -2.0, u'oversell': -2.0,
                 'affronted': -1.0, u'interrogated': -2.0, u'angers': -3.0, u'arrests': -2.0, u'rescues': 2.0,
                 'idiotic': -3.0, u'fraudsters': -4.0, u'heavyhearted': -2.0, u'bad': -3.0, u'ban': -2.0,
                 'ruins': -2.0, u'ethical': 2.0, u'erroneous': -2.0, u'mandatory': -1.0, u'disaster': -2.0,
                 'fascinating': 3.0, u'thwarting': -2.0, u'sincerest': 2.0, u'horrendous': -3.0, u'fail': -2.0,
                 'disturbing': -2.0, u'resigned': -1.0, u'best': 3.0, u'clarifies': 2.0, u'pressured': -2.0,
                 'green wash': -3.0, u'meditative': 1.0, u'hopefully': 2.0, u'scorn': -2.0, u'lethargic': -2.0,
                 'indecisive': -2.0, u'lazy': -1.0, u'rotflol': 4.0, u'extend': 1.0, u'admiring': 3.0, u'felony': -3.0,
                 'restricting': -2.0, u'weak': -2.0, u'ignorance': -2.0, u'weary': -2.0, u'wtf': -4.0, u'debt': -2.0,
                 'improve': 2.0, u'pity': -2.0, u'protect': 1.0, u'accident': -2.0, u'disdain': -2.0, u'ill': -2.0,
                 'adventures': 2.0, u'demanded': -1.0, u'agonise': -3.0, u'indoctrinating': -2.0, u'monopolize': -2.0,
                 'disappears': -1.0, u'overstatements': -2.0, u'peacefully': 2.0, u'honouring': 2.0,
                 'irresponsible': 2.0, u'greenwashing': -3.0, u'greenwashers': -3.0, u'persecuting': -2.0,
                 'trust': 1.0, u'trickery': -2.0, u'parley': -1.0, u'condemned': -2.0, u'victimizing': -3.0,
                 'bothers': -2.0, u'confident': 2.0, u'startled': -2.0, u'interest': 1.0, u'jackass': -4.0,
                 'incompetent': -2.0, u'easy': 1.0, u'prosperous': 3.0, u'attacked': -1.0, u'sunshine': 2.0,
                 'excite': 3.0, u'wowow': 4.0, u'doubts': -1.0, u'haters': -3.0, u'censored': -2.0, u'cunt': -5.0,
                 'gracious': 3.0, u'distorts': -2.0, u'inhibit': -1.0, u'save': 2.0, u'harms': -2.0,
                 'illiteracy': -2.0, u'roflmao': 4.0, u'ugly': -3.0, u'slam': -2.0, u'stopping': -1.0,
                 'murders': -2.0, u'dehumanizes': -2.0, u'chilling': -1.0, u'mistake': -2.0, u'pessimistic': -2.0,
                 'vulnerability': -2.0, u'congratulation': 2.0, u'unresearched': -2.0, u'dumped': -2.0,
                 'defeated': -2.0, u'fakes': -3.0, u'shame': -2.0, u'dizzy': -1.0, u'moping': -1.0, u'appalling': -2.0,
                 'greenwash': -3.0, u'disappear': -1.0, u'laughting': 1.0, u'constrained': -2.0, u'vindicate': 2.0,
                 'misunderstood': -2.0, u'disparages': -2.0, u'pardoning': 2.0, u'damages': -3.0, u'disparaged': -2.0,
                 'naive': -2.0, u'harming': -2.0, u'acquitting': 2.0, u'blames': -2.0, u'misery': -2.0, u'tops': 2.0,
                 'evil': -3.0, u'greeted': 1.0, u'delight': 3.0, u'consents': 2.0, u'outmaneuvered': -2.0,
                 'jealous': -2.0, u'opportunity': 2.0, u'blamed': -2.0, u'shitty': -3.0, u'failing': -2.0,
                 'inspires': 2.0, u'greatest': 3.0, u'detained': -2.0, u'flops': -2.0, u'dipshit': -3.0,
                 'bereave': -2.0, u'appease': 2.0, u'sentence': -2.0, u'agog': 2.0, u'envious': -2.0,
                 'disguise': -1.0, u'thanks': 2.0, u'victim': -3.0, u'swears': -2.0, u'resigning': -1.0, u'yes': 1.0,
                 'convivial': 2.0, u'enlighten': 2.0, u'rapturous': 4.0, u'terrific': 4.0, u'ease': 2.0,
                 'assassination': -3.0, u'passive': -1.0, u'advanced': 1.0, u'beloved': 3.0, u'prison': -2.0,
                 'moody': -1.0, u'expelled': -2.0, u'threatens': -2.0, u'mocked': -2.0, u'insensitive': -2.0,
                 'perfects': 2.0, u'celebrates': 3.0, u'bastards': -5.0, u'dreams': 1.0, u'disadvantage': -2.0,
                 'desire': 1.0, u'gift': 2.0, u'dishonest': -2.0, u'disillusioned': -2.0, u'notorious': -2.0,
                 'honored': 2.0, u'drowned': -2.0, u'stereotype': -2.0, u'exonerates': 2.0, u'proudly': 2.0,
                 'dead': -3.0, u'coziness': 2.0, u'escape': -1.0, u'dear': 2.0, u'prick': -5.0, u'bore': -2.0,
                 'perfected': 2.0, u'enemies': -2.0, u'denies': -2.0, u'congratulate': 2.0, u'humor': 2.0,
                 'combat': -1.0, u'creative': 2.0, u'disheartened': -2.0, u'honoured': 2.0, u'rebellion': -2.0,
                 'denied': -2.0, u'pollutes': -2.0, u'polluter': -2.0, u'beating': -1.0, u'adorable': 3.0,
                 'bamboozle': -2.0, u'alarmists': -2.0, u'bold': 2.0, u'disappeared': -1.0, u'losing': -3.0,
                 'super': 3.0, u'limitation': -1.0, u'boycotts': -2.0, u'derailed': -2.0, u'attacks': -1.0,
                 'accepts': 1.0, u'choke': -2.0, u'blithe': 2.0, u'despair': -3.0, u'ensure': 1.0, u'cherish': 2.0,
                 'commit': 1.0, u'disqualified': -2.0, u'dilemma': -1.0, u'lied': -2.0, u'wasting': -2.0,
                 'prisoners': -2.0, u'detention': -2.0, u'delighted': 3.0, u'obscene': -2.0, u'thankful': 2.0,
                 'unstable': -2.0, u'stall': -2.0, u'frightened': -2.0, u'strangely': -1.0, u'annoyance': -2.0,
                 'deception': -3.0, u'support': 2.0, u'unfocused': -2.0, u'fight': -1.0, u'fucking': -4.0,
                 'war': -2.0, u'happy': 3.0, u'lowest': -1.0, u'starve': -2.0, u'underestimated': -1.0,
                 'overjoyed': 4.0, u'forgetful': -2.0, u'vitality': 3.0, u'failure': -2.0, u'underestimates': -1.0,
                 'astonished': 2.0, u'true': 2.0, u'congratulations': 2.0, u'injury': -2.0, u'invincible': 2.0,
                 'bargain': 2.0, u'ruined': -2.0, u'adore': 3.0, u'torturing': -4.0, u'faking': -3.0,
                 'propaganda': -2.0, u'fulfills': 2.0, u'promises': 1.0, u'looms': -1.0, u'disgrace': -2.0,
                 'scandalous': -3.0, u'sinful': -3.0, u'assassinations': -3.0, u'soothe': 3.0, u'promised': 1.0,
                 'sprightly': 2.0, u'pileup': -1.0, u'annoying': -2.0, u'shit': -4.0, u'oversimplification': -2.0,
                 'faithful': 3.0, u'eerie': -2.0, u'interested': 2.0, u'looses': -3.0, u'ambitious': 2.0,
                 'confusing': -2.0, u'misinterpreted': -2.0, u'denier': -2.0, u'scream': -2.0, u'assfucking': -4.0,
                 'outreach': 2.0, u'smile': 2.0, u'funerals': -1.0, u'died': -3.0, u'derail': -2.0, u'warn': -2.0,
                 'apologizing': -1.0, u'cheated': -3.0, u'apology': -1.0, u'restores': 1.0, u'loyal': 3.0,
                 'cheater': -3.0, u'optionless': -2.0, u'menaced': -2.0, u'restored': 1.0, u'bereaving': -2.0,
                 'remarkable': 2.0, u'drained': -2.0, u'rob': -2.0, u'relieve': 1.0, u'grateful': 3.0, u'battle': -1.0,
                 'polluted': -2.0, u'devoted': 3.0, u'soothed': 3.0, u'misread': -1.0, u'anticipation': 1.0,
                 'praises': 3.0, u'deceitful': -3.0, u'honoring': 2.0, u'disgusting': -3.0, u'abhorrent': -3.0,
                 'amaze': 2.0, u'praised': 3.0, u'dissatisfied': -2.0, u'negativity': -2.0, u'terror': -3.0,
                 'retreat': -1.0, u'fatigues': -2.0, u'slash': -2.0, u'advantage': 2.0, u'apeshit': -3.0,
                 'gloomy': -2.0, u'mourn': -2.0, u'fatigued': -2.0, u'forgiving': 1.0, u'feeble': -2.0, u'cool': 1.0,
                 'impressive': 3.0, u'solves': 1.0, u'die': -3.0, u'accidentally': -2.0, u'leave': -1.0,
                 'solved': 1.0, u'excellence': 3.0, u'denounces': -2.0, u'unaware': -2.0, u'attracting': 2.0,
                 'prevent': -1.0, u'brave': 2.0, u'fearing': -2.0, u'insignificant': -2.0, u'sigh': -2.0,
                 'obsolete': -2.0, u'comforting': 2.0, u'helpless': -2.0, u'irritated': -3.0, u'acrimonious': -3.0,
                 'rapist': -4.0, u'self-deluded': -2.0, u'curse': -1.0, u'jeopardy': -2.0, u'celebrated': 3.0,
                 'havoc': -2.0, u'pleased': 3.0, u'suspect': -1.0, u'shared': 1.0, u'falling': -1.0, u'axed': -1.0,
                 'supporting': 1.0, u'unsure': -1.0, u'honour': 2.0, u'funeral': -1.0, u'victimized': -3.0,
                 'envy': -1.0, u'confused': -2.0, u'persecuted': -2.0, u'oversimplify': -2.0, u'messing up': -2.0,
                 'accomplishes': 2.0, u'coerced': -2.0, u'brilliant': 4.0, u'guilty': -3.0, u'proud': 2.0,
                 'pseudoscience': -3.0, u'accomplished': 2.0, u'ineffective': -2.0, u'weird': -2.0,
                 'motherfucking': -5.0, u'breathtaking': 5.0, u'charmless': -3.0, u'love': 3.0, u'humour': 2.0,
                 'hardier': 2.0, u'bloody': -3.0, u'marvelous': 3.0, u'betraying': -3.0, u'fake': -3.0, u'scam': -2.0,
                 'crisis': -3.0, u'disguising': -1.0, u'sympathetic': 2.0, u'dolorous': -2.0, u'cherishes': 2.0,
                 'homesick': -2.0, u'unimpressed': -2.0, u'positive': 2.0, u'angry': -3.0, u'resigns': -1.0,
                 'cherished': 2.0, u'loving': 2.0, u'conciliating': 2.0, u'riot': -2.0, u'share': 1.0,
                 'swearing': -2.0, u'downhearted': -2.0, u'wooo': 4.0, u'drown': -2.0, u'dismal': -2.0,
                 'degrade': -2.0, u'douche': -3.0, u'niggas': -5.0, u'pretend': -1.0, u'flu': -2.0, u'inflamed': -2.0,
                 'flagship': 2.0, u'wanker': -3.0, u'drags': -1.0, u'hope': 2.0, u'growing': 1.0, u'detached': -1.0,
                 'stimulating': 2.0, u'lighthearted': 1.0, u'admired': 3.0, u'dedicated': 2.0, u'lobbying': -2.0,
                 'awesome': 4.0, u'fuck': -4.0, u'disbelieve': -2.0, u'hides': -1.0, u'glamourous': 3.0, u'chic': 2.0,
                 'provoke': -1.0, u'unlovable': -2.0, u'validated': 1.0, u'bankrupt': -3.0, u'fuming': -2.0,
                 'secured': 2.0, u'agonizing': -3.0, u'immune': 1.0, u'misleading': -3.0, u'endorsement': 2.0,
                 'dehumanizing': -2.0, u'secures': 2.0, u'unbelievable': -1.0, u'irrational': -1.0, u'critics': -2.0,
                 'averted': -1.0, u'disgusted': -3.0, u'heartbreaking': -3.0, u'mad': -3.0, u'improving': 2.0,
                 'heroes': 2.0, u'destructive': -3.0, u'fraudulence': -4.0, u'natural': 1.0, u'disconsolate': -2.0,
                 'stupidly': -2.0, u'amuse': 3.0, u'nosey': -2.0, u'thorny': -2.0, u'youthful': 2.0, u'deceive': -3.0,
                 'offend': -2.0, u'worsens': -3.0, u'cute': 2.0, u'foreclosure': -2.0, u'shaky': -2.0, u'wishing': 1.0,
                 'unacceptable': -2.0, u'suicide': -2.0, u'playful': 2.0, u'fatalities': -3.0, u'cuts': -1.0,
                 'lovelies': 3.0, u'irresolute': -2.0, u'blocked': -1.0, u'dreading': -2.0, u'avid': 2.0,
                 'thank': 2.0, u'interesting': 2.0, u'torn': -2.0, u'troubles': -2.0, u'abhorred': -3.0,
                 'attraction': 2.0, u'swindle': -3.0, u'undermines': -2.0, u'overreacted': -2.0, u'lonely': -2.0,
                 'accusations': -2.0, u'captivated': 3.0, u'devastated': -2.0, u'reject': -1.0, u'sarcastic': -2.0,
                 'singleminded': -2.0, u'compelled': 1.0, u'wealthy': 2.0, u'bullshit': -4.0, u'intrigues': 1.0,
                 'undermining': -2.0, u'drop': -1.0, u'does not work': -3.0, u'careless': -2.0, u'vexation': -2.0,
                 'snubbed': -2.0, u'stalling': -2.0, u'fired': -2.0, u'crushing': -1.0, u'yeah': 1.0,
                 'breakthrough': 3.0, u'avoided': -1.0, u'disasters': -2.0, u'amusement': 3.0, u'hysteria': -3.0,
                 'giddy': -2.0, u'accomplish': 2.0, u'infuriated': -2.0, u'monopolizes': -2.0, u'irony': -1.0,
                 'agonises': -3.0, u'worshiped': 3.0, u'cancels': -1.0, u'infuriates': -2.0, u'collisions': -2.0,
                 'condemns': -2.0, u'trauma': -3.0, u'hacked': -1.0, u'agonised': -3.0, u'inaction': -2.0,
                 'phobic': -2.0, u'vicious': -2.0, u'disrespect': -2.0, u'felonies': -3.0, u'advantages': 2.0,
                 'crazier': -2.0, u'ominous': 3.0, u'care': 2.0, u'envies': -1.0, u'disguised': -1.0,
                 'collapsing': -2.0, u'impose': -1.0, u'honest': 2.0, u'disguises': -1.0, u'funky': 2.0,
                 'apologising': -1.0, u'winwin': 3.0, u'aboard': 1.0, u'bothersome': -2.0, u'outcry': -2.0,
                 'entrusted': 2.0, u'neglect': -2.0, u'blind': -1.0, u'suspend': -1.0, u'surviving': 2.0,
                 'suspended': -1.0, u'suing': -2.0, u'lags': -2.0, u'agonising': -3.0, u'ashame': -2.0,
                 'rageful': -2.0, u'monopolizing': -2.0, u'derision': -2.0, u'oversimplifies': -2.0,
                 'encourages': 2.0, u'stifled': -1.0, u'persecute': -2.0, u'legally': 1.0, u'oversimplified': -2.0,
                 'seduced': -1.0, u'hug': 2.0, u'appreciates': 2.0, u'alas': -1.0, u'slashed': -2.0,
                 'appreciated': 2.0, u'petrified': -2.0, u'fuking': -4.0, u'lmao': 4.0, u'depressed': -2.0,
                 'favors': 2.0, u'optimism': 2.0, u'protected': 1.0, u'damned': -4.0, u'proactive': 2.0,
                 'usefulness': 2.0, u'prospect': 1.0, u'questionable': -2.0, u'illness': -2.0, u'contentious': -2.0,
                 'jewels': 1.0, u'sad': -2.0, u'conspiracy': -3.0, u'distorted': -2.0, u'anger': -3.0,
                 'shocked': -2.0, u'violates': -2.0, u'defenseless': -2.0, u'destroy': -3.0, u'relaxed': 2.0,
                 'deniers': -2.0, u'pain': -2.0, u'oppressive': -2.0, u'betrayal': -3.0, u'suspects': -1.0,
                 'insanity': -2.0, u'unmatched': 1.0, u'cleared': 1.0, u'envying': -1.0, u'lawl': 3.0,
                 "can't stand": -3.0, u'steadfast': 2.0, u'discarding': -1.0, u'adopt': 1.0, u'axe': -1.0,
                 'cheat': -3.0, u'infuriate': -2.0, u'applauding': 2.0, u'bright': 1.0, u'scoop': 3.0,
                 'aggressive': -2.0, u'stressor': -2.0, u'help': 2.0, u'woow': 4.0, u'strangled': -2.0, u'dick': -4.0,
                 'robs': -2.0, u'embittered': -2.0, u'crime': -3.0, u'dejecting': -2.0, u'welcomed': 2.0,
                 'tears': -2.0, u'travesty': -2.0, u'defenders': 2.0, u'outrage': -3.0, u'dreaded': -2.0,
                 'dispute': -2.0, u'rejoiced': 4.0, u'haplessness': -2.0, u'satisfied': 2.0, u'rejoices': 4.0,
                 'hailed': 2.0, u'consolable': 2.0, u'unethical': -2.0, u'justified': 2.0, u'celebrate': 3.0,
                 'astounds': 3.0, u'verdicts': -1.0, u'wrathful': -3.0, u'sabotage': -2.0, u'obliterate': -2.0,
                 'imbecile': -3.0, u'superb': 5.0, u'worried': -3.0, u'jokes': 2.0, u'overreaction': -2.0,
                 'spam': -2.0, u'prevents': -1.0, u'disparage': -2.0, u'worrying': -3.0, u'vision': 1.0,
                 'ignored': -2.0, u'lethargy': -2.0, u'imposing': -1.0, u'violated': -2.0, u'whitewash': -3.0,
                 'fucktard': -4.0, u'dickhead': -4.0, u'slashing': -2.0, u'ignores': -1.0, u'rewarded': 2.0,
                 'encouraged': 2.0, u'fails': -2.0, u'enlightening': 2.0, u'fascinated': 3.0, u'belittled': -2.0,
                 'mope': -1.0, u'enjoys': 2.0, u'moaned': -2.0, u'fascinates': 3.0, u'fearless': 2.0, u'pained': -2.0,
                 'killing': -3.0, u'blame': -2.0, u'jovial': 2.0, u'awards': 3.0, u'hurts': -2.0, u'moans': -2.0,
                 'spark': 1.0, u'grieved': -2.0, u'undermine': -2.0, u'frisky': 2.0, u'yeees': 2.0, u'tout': -2.0,
                 'disappointment': -2.0, u'protesters': -2.0, u'cornered': -2.0, u'sulky': -2.0, u'cancer': -1.0,
                 'smartest': 2.0, u'accusation': -2.0, u'exploit': -2.0, u'grants': 1.0, u'anti': -1.0,
                 u'cancel': -1.0, u'perpetrators': -2.0, u'bizarre': -2.0, u'panics': -3.0, u'better': 2.0,
                 u'screams': -2.0, u'punishes': -2.0, u'collides': -1.0, u'capable': 1.0, u'swift': 2.0,
                 u'brainwashing': -3.0, u'jaunty': 2.0, u'punished': -2.0, u'peaceful': 2.0, u'ruining': -2.0,
                 u'aggressions': -2.0, u'shortages': -2.0, u'blessing': 3.0, u'mocking': -2.0, u'unified': 1.0,
                 u'suspected': -1.0, u'careful': 2.0, u'spirit': 1.0, u'colluding': -3.0, u'sedition': -2.0,
                 u'apologised': -1.0, u'apologises': -1.0, u'cancelled': -1.0, u'abducted': -2.0, u'falsified': -3.0,
                 u'huckster': -2.0, u'raptured': 2.0, u'unsupported': -2.0, u'sincere': 2.0, u'oks': 2.0,
                 u'dubious': -2.0, u'blah': -2.0, u'bias': -1.0, u'embrace': 1.0, u'raptures': 2.0, u'ironic': -1.0,
                 u'engages': 1.0, u'fame': 1.0, u'worry': -3.0, u'resentful': -2.0, u'harsh': -2.0, u'dithering': -2.0,
                 u'granted': 1.0, u'underestimate': -1.0, u'weakness': -2.0, u'struggling': -2.0, u'favorited': 2.0,
                 u'applaud': 2.0, u'boosted': 1.0, u'intimidation': -2.0, u'cheers': 2.0, u'favorites': 2.0,
                 u'cheery': 3.0, u'weep': -2.0, u'complained': -2.0, u'longing': -1.0, u'charges': -2.0, u'amazes': 2.0,
                 u'disregards': -2.0, u'no': -1.0, u'severe': -2.0, u'solve': 1.0, u'inability': -2.0, u'no fun': -3.0,
                 u'reward': 2.0, u'amazed': 2.0, u'charged': -3.0, u'diffident': -2.0, u'robing': -2.0,
                 u'exaggerating': -2.0, u'pissing': -3.0, u'kill': -3.0, u'greetings': 2.0, u'madness': -3.0,
                 u'alarmist': -2.0, u'death': -2.0, u'clueless': -2.0, u'deceiving': -3.0, u'dauntless': 2.0,
                 u'adventurous': 2.0, u'disputing': -2.0, u'mournful': -2.0, u'joyful': 3.0, u'starving': -2.0,
                 u'kills': -3.0, u'reassured': 1.0, u'earnest': 2.0, u'boycotted': -2.0, u'accepted': 1.0,
                 u'disappointed': -2.0, u'vague': -2.0, u'tremulous': -2.0, u'distrustful': -3.0, u'possessive': -2.0,
                 u'terrorize': -3.0, u'endorses': 2.0, u'greeting': 1.0, u'miracle': 4.0, u'discarded': -1.0,
                 u'benefit': 2.0, u'laughing': 1.0, u'dirtier': -2.0, u'passionate': 2.0, u'endorsed': 2.0,
                 u'burdens': -2.0, u'hysterics': -3.0, u'exposed': -1.0, u'pushy': -1.0, u'short-sightedness': -2.0,
                 u'slavery': -3.0, u'exposes': -1.0, u'intact': 2.0, u'gross': -2.0, u'noob': -2.0, u'douchebag': -3.0,
                 u'slick': 2.0, u'legal': 1.0, u'deficit': -2.0, u'restoring': 1.0, u'apocalyptic': -2.0,
                 u'destroys': -3.0, u'biased': -2.0, u'welcome': 2.0, u'racism': -3.0, u'sadden': -2.0, u'lmfao': 4.0,
                 u'indestructible': 2.0, u'stereotyped': -2.0, u'exultantly': 3.0, u'disparaging': -2.0,
                 u'broken': -1.0, u'stops': -1.0, u'exciting': 3.0, u'fondness': 2.0, u'joyfully': 3.0,
                 u'contagion': -2.0, u'zealous': 2.0, u'smear': -2.0, u'cares': 2.0, u'favorite': 2.0, u'tumor': -2.0,
                 u'boldly': 2.0, u'scornful': -2.0, u'masterpieces': 4.0, u'perturbed': -2.0, u'protests': -2.0,
                 u'lively': 2.0, u'apologize': -1.0, u'annoys': -2.0, u'empathetic': 2.0, u'loathed': -3.0,
                 u'innovates': 1.0, u'exonerated': 2.0, u'totalitarian': -2.0, u'betrays': -3.0, u'lol': 3.0,
                 u'mindless': -2.0, u'racist': -3.0, u'futile': 2.0, u'decisive': 1.0, u'hysterical': -3.0,
                 u'allergic': -2.0, u'ranters': -3.0, u'exasperated': 2.0, u'mischief': -1.0, u'mourns': -2.0,
                 u'vested': 1.0, u'unsettled': -1.0, u'stressors': -2.0, u'delayed': -1.0, u'strikes': -1.0,
                 u'sophisticated': 2.0, u'fascists': -2.0, u'promote': 1.0, u'irreversible': -1.0, u'abused': -3.0,
                 u'fraud': -4.0, u'rage': -2.0, u'overreacts': -2.0, u'resolving': 2.0, u'treasure': 2.0,
                 u'dirty': -2.0, u'abuses': -3.0, u'ennui': -2.0, u'deadlock': -2.0, u'agree': 1.0, u'affection': 3.0,
                 u'illnesses': -2.0, u'leaked': -1.0, u'fright': -2.0, u'exhausted': -2.0, u'certain': 1.0,
                 u'bamboozled': -2.0, u'censor': -2.0, u'tranquil': 2.0, u'amused': 3.0, u'bamboozles': -2.0,
                 u'casualty': -2.0, u'selfish': -3.0, u'strikers': -2.0, u'pensive': -1.0, u'idiot': -3.0,
                 u'conflictive': -2.0, u'short-sighted': -2.0, u'undermined': -2.0, u'fools': -2.0, u'dismayed': -2.0,
                 u'victimize': -3.0, u'gaining': 2.0, u'obsessed': 2.0, u'overreact': -2.0, u'important': 2.0,
                 u'fresh': 1.0, u'mourned': -2.0, u'applause': 2.0, u'apathy': -3.0, u'not working': -3.0,
                 u'fraudulent': -4.0, u'doubted': -1.0, u'restricted': -2.0, u'burdening': -2.0, u'liar': -3.0,
                 u'forget': -1.0, u'vile': -3.0, u'lack': -2.0, u'pique': -2.0, u'thoughtful': 2.0, u'sappy': -1.0,
                 u'dreadful': -3.0, u'catastrophe': -3.0, u'opportunities': 2.0, u'riots': -2.0, u'revengeful': -2.0,
                 u'robber': -2.0, u'remorse': -2.0, u'enjoying': 2.0, u'restrict': -2.0, u'distorting': -2.0,
                 u'libelous': -2.0, u'infringement': -2.0, u'carefree': 1.0, u'saved': 2.0, u'crestfallen': -2.0,
                 u'fan': 3.0, u'rape': -4.0, u'awful': -3.0, u'robed': -2.0, u'fag': -3.0, u'fad': -2.0,
                 u'abandoned': -2.0, u'elated': 3.0, u'heaven': 2.0, u'misinformation': -2.0, u'fearful': -2.0,
                 u'liars': -3.0, u'mistaking': -2.0, u'enrapture': 3.0, u'son-of-a-bitch': -5.0, u'methodical': 2.0,
                 u'vivacious': 3.0, u'appreciating': 2.0, u'apologizes': -1.0, u'darkness': -1.0, u'skeptic': -2.0,
                 u'disruptions': -2.0, u'zealots': -2.0, u'overload': -1.0, u'crush': -1.0, u'apologized': -1.0,
                 u'undecided': -1.0, u'starved': -2.0, u'falsify': -3.0, u'escaping': -1.0, u'unprofessional': -2.0,
                 u'loose': -3.0, u'overstatement': -2.0, u'motherfucker': -5.0, u'rigged': -1.0, u'disastrous': -3.0,
                 u'hopelessness': -2.0, u'yummy': 3.0, u'strong': 2.0, u'untarnished': 2.0, u'tragedy': -2.0,
                 u'cock': -5.0, u'inspired': 2.0, u'masterpiece': 4.0, u'horrified': -3.0, u'gleeful': 3.0,
                 u'heartbroken': -3.0, u'murdering': -3.0, u'dehumanized': -2.0, u'whimsical': 1.0, u'cowardly': -2.0,
                 u'snub': -2.0, u'deject': -2.0, u'irritate': -3.0, u'wavering': -1.0, u'promoting': 1.0,
                 u'fraudster': -4.0, u'hurrah': 5.0, u'inquisition': -2.0, u'diamond': 1.0, u'brisk': 2.0,
                 u'problem': -2.0, u'excuse': -1.0, u'broke': -1.0, u'retained': -1.0, u'doom': -2.0, u'glad': 3.0,
                 u'unfulfilled': -2.0, u'offender': -2.0, u'sucks': -3.0, u'offended': -2.0, u'beautiful': 3.0,
                 u'stubborn': -2.0, u'embarrassing': -2.0, u'virtuous': 2.0, u'neglected': -2.0, u'accept': 1.0,
                 u'boycott': -2.0, u'collision': -2.0, u'protects': 1.0, u'exclude': -1.0, u'condemn': -2.0,
                 u'unappreciated': -2.0, u'huge': 1.0, u'prosecution': -1.0, u'obnoxious': -3.0, u'calms': 2.0,
                 u'awkward': -2.0, u'terribly': -3.0, u'needy': -2.0, u'comfort': 2.0, u'ratified': 2.0,
                 u'abhors': -3.0, u'hugs': 2.0, u'peril': -2.0, u'controversially': -2.0, u'disgraced': -2.0,
                 u'questioning': -1.0, u'adventure': 2.0, u'numb': -1.0, u'hooliganism': -2.0, u'refuse': -2.0,
                 u'criticize': -2.0, u'n00b': -2.0, u'spiteful': -2.0, u'wishes': 1.0, u'dread': -2.0,
                 u'deafening': -1.0, u'pay': -1.0, u'pleasure': 3.0, u'dream': 1.0, u'enslaved': -2.0,
                 u'heartfelt': 3.0, u'outraged': -3.0, u'committed': 1.0, u'hell': -4.0, u'smiling': 2.0,
                 u'suffer': -2.0, u'trouble': -2.0, u'arrogant': -2.0, u'messed': -2.0, u'pray': 1.0, u'solving': 1.0,
                 u'averts': -1.0, u'bummer': -2.0, u'nifty': 2.0, u'fool': -2.0, u'hurting': -2.0, u'good': 3.0,
                 u'motivated': 2.0, u'abandons': -2.0, u'fuckface': -4.0, u'moaning': -2.0, u'belittle': -2.0,
                 u'complain': -2.0, u'desperately': -3.0, u'slicker': 2.0, u'imprisoned': -2.0, u'scumbag': -4.0,
                 u'bless': 2.0, u'stopped': -1.0, u'reassures': 1.0, u'shocking': -2.0, u'disorganized': -2.0,
                 u'neglects': -2.0, u'harm': -2.0, u'shock': -2.0, u'restless': -2.0, u'noble': 2.0, u'resolute': 2.0,
                 u'hard': -1.0, u'oppressed': -2.0, u'gun': -1.0, u'punitive': -2.0, u'deride': -2.0,
                 u'suspecting': -1.0, u'seditious': -2.0, u'gullible': -2.0, u'missed': -2.0, u'ftw': 3.0,
                 u'miss': -2.0, u'childish': -2.0, u'disquiet': -2.0, u'jolly': 2.0, u'safety': 1.0, u'paradise': 3.0,
                 u'offline': -1.0, u'ass': -4.0, u'nervously': -2.0, u'warm': 1.0, u'bully': -2.0, u'pathetic': -2.0,
                 u'dirt': -2.0, u'favored': 2.0, u'commits': 1.0, u'forgive': 1.0, u'pleasant': 3.0, u'brightest': 2.0,
                 u'dire': -3.0, u'backed': 1.0, u'hapless': -2.0, u'heroic': 3.0, u'disadvantaged': -2.0,
                 u'benefits': 2.0, u'stampede': -2.0, u'success': 2.0, u'cheering': 2.0, u'threat': -2.0,
                 u'fallen': -2.0, u'top': 2.0, u'unhealthy': -2.0, u'stabs': -2.0, u'contender': -1.0,
                 u'disregarded': -2.0, u'shameful': -2.0, u'sympathy': 2.0, u'humourous': 2.0, u'defects': -3.0,
                 u'totalitarianism': -2.0, u'touting': -2.0, u'bullied': -2.0, u'validate': 1.0, u'regret': -2.0,
                 u'moan': -2.0, u'kinder': 2.0, u'threatening': -2.0, u'revive': 2.0, u'wonderful': 4.0,
                 u'shamed': -2.0, u'dumbass': -3.0, u'imperfect': -2.0, u'rescue': 2.0, u'relieved': 2.0,
                 u'convinces': 1.0, u'appreciation': 2.0, u'luckily': 3.0, u'treasures': 2.0, u'convinced': 1.0,
                 u'grace': 1.0, u'relieves': 1.0, u'kind': 2.0, u'picturesque': 2.0, u'disrespected': -2.0,
                 u'grey': -1.0, u'spirited': 2.0, u'hooligans': -2.0, u'risks': -2.0, u'insulted': -2.0,
                 u'restful': 2.0, u'sentenced': -2.0, u'cleaner': 2.0, u'motivation': 1.0, u'outstanding': 5.0,
                 u'strengthen': 2.0, u'suspicious': -2.0, u'defect': -3.0, u'rewards': 2.0, u'sentences': -2.0,
                 u'blissful': 3.0, u'vulnerable': -2.0, u'misrepresentation': -2.0, u'speculative': -2.0,
                 u'trapped': -2.0, u'lackadaisical': -2.0, u'applauded': 2.0, u'aggravating': -2.0, u'serene': 2.0,
                 u'contestable': -2.0, u'frauds': -4.0, u'approves': 2.0, u'inconvenience': -2.0, u'reach': 1.0,
                 u'charm': 3.0, u'significant': 1.0, u'accepting': 1.0, u'boycotting': -2.0, u'approved': 2.0,
                 u'funnier': 4.0, u'unequal': -1.0, u'squelched': -1.0, u'once-in-a-lifetime': 3.0, u'clear': 1.0,
                 u'greenwasher': -3.0, u'clean': 2.0, u'hindrance': -2.0, u'fainthearted': -2.0, u'amusements': 3.0,
                 u'dragged': -1.0, u'dodging': -2.0, u'stunned': -2.0, u'agonize': -3.0, u'fond': 2.0,
                 u'degrades': -2.0, u'aghast': -2.0, u'dejects': -2.0, u'shares': 1.0, u'carefully': 2.0,
                 u'defender': 2.0, u'degraded': -2.0, u'fine': 2.0, u'distressing': -2.0, u'aggravate': -2.0,
                 u'justice': 2.0, u'nervous': -2.0, u'ruin': -2.0, u'unhappy': -2.0, u'penalty': -2.0, u'failed': -2.0,
                 u'betray': -3.0, u'pretty': 1.0, u'indifference': -2.0, u'devastate': -2.0, u'gains': 2.0,
                 u'banned': -2.0, u'revered': 2.0, u'courage': 2.0, u'hid': -1.0, u'pretending': -1.0, u'damnit': -4.0,
                 u'frightening': -3.0, u'distraction': -2.0, u'enemy': -2.0, u'resolve': 2.0, u'contagious': -1.0,
                 u'boost': 1.0, u'disregarding': -2.0, u'violent': -3.0, u'thwarts': -2.0, u'mistakes': -2.0,
                 u'withdrawal': -3.0, u'poisoned': -2.0, u'courteous': 2.0, u'relentless': -1.0, u'repulsed': -2.0,
                 u'insane': -2.0, u'cramp': -1.0, u'dump': -1.0, u'dumb': -3.0, u'tender': 2.0, u'threats': -2.0,
                 u'wow': 4.0, u'please': 1.0, u'rejecting': -1.0, u'woo': 3.0, u'determined': 2.0,
                 u'right direction': 3.0, u'silly': -1.0, u'piss': -4.0, u'cancelling': -1.0, u'vindicated': 2.0,
                 u'hardship': -2.0, u'fidgety': -2.0, u'intimidated': -2.0, u'persecutes': -2.0, u'unstoppable': 2.0,
                 u'vindicates': 2.0, u'fatality': -3.0, u'betrayed': -3.0, u'intimidates': -2.0, u'prospects': 1.0,
                 u'improved': 2.0, u'hesitant': -2.0, u'influential': 2.0, u'offending': -2.0, u'chastising': -3.0,
                 u'timorous': -2.0, u'adored': 3.0, u'improves': 2.0, u'scams': -2.0, u'forgotten': -1.0,
                 u'poverty': -1.0, u'cynic': -2.0, u'faggots': -3.0, u'liked': 2.0, u'distress': -2.0, u'drunk': -2.0,
                 u'sweet': 2.0, u'stuck': -2.0, u'rofl': 4.0, u'deceit': -3.0, u'eviction': -1.0, u'likes': 2.0,
                 u'vindicating': 2.0, u'improvement': 2.0, u'worthless': -2.0, u'victimizes': -3.0, u'some kind': 0.0,
                 u'dud': -2.0, u'damn': -4.0, u'threaten': -2.0, u'empty': -1.0, u'affectionate': 3.0, u'fire': -2.0,
                 u'cruelty': -3.0, u'disruptive': -2.0, u'misbehaving': -2.0, u'demand': -1.0, u'gag': -2.0,
                 u'poised': -2.0, u'loom': -1.0, u'misunderstands': -2.0, u'solid': 2.0, u'postponing': -1.0,
                 u'straight': 1.0, u'cashing in': -2.0, u'terrorizes': -3.0, u'admire': 3.0, u'healthy': 2.0,
                 u'fud': -3.0, u'substantial': 1.0, u'error': -2.0, u'fun': 4.0, u'flees': -1.0, u'walkouts': -2.0,
                 u'costly': -2.0, u'hoping': 2.0, u'backing': 2.0, u'overlooked': -1.0, u'astound': 3.0, u'hoax': -2.0,
                 u'obstacle': -2.0, u'frantic': -1.0, u'beautifully': 3.0, u'rig': -1.0, u'alone': -2.0, u'funny': 4.0,
                 u'unworthy': -2.0, u'stimulates': 1.0, u'choking': -2.0, u'grant': 1.0, u'perpetrator': -2.0,
                 u'engrossed': 1.0, u'stimulated': 1.0, u'madly': -3.0, u'grand': 3.0, u'esteemed': 2.0, u'itchy': -2.0,
                 u'conflict': -2.0, u'displeased': -2.0, u'absentees': -1.0, u'praising': 3.0, u'comprehensive': 2.0,
                 u'overweight': -1.0, u'alert': -1.0, u'absolved': 2.0, u'haunting': 1.0, u'robust': 2.0,
                 u'timid': -2.0, u'starves': -2.0, u'cocksuckers': -5.0, u'regretting': -2.0, u'cheer': 2.0,
                 u'inspirational': 2.0, u'clears': 1.0, u'absolving': 2.0, u'appalled': -2.0, u'abilities': 2.0,
                 u'exploits': -2.0, u'reliant': 2.0, u'competitive': 2.0, u'exonerating': 2.0, u'cocky': -2.0,
                 u'vigilant': 3.0, u'useful': 2.0, u'praying': 1.0, u'cut': -1.0, u'hated': -3.0, u'eager': 2.0,
                 u'questioned': -1.0, u'crying': -2.0, u'eery': -2.0, u'excited': 3.0, u'hates': -3.0, u'useless': -2.0,
                 u'motivating': 2.0, u'complains': -2.0, u'emergency': -2.0, u'demands': -1.0, u'big': 1.0,
                 u'joyless': -2.0, u'condemnation': -2.0, u'rotflmfao': 4.0, u'matters': 1.0, u'suffering': -2.0,
                 u'dearly': 3.0, u'like': 2.0, u'skeptical': -2.0, u'worsening': -3.0, u'imposed': -1.0, u'lost': -3.0,
                 u'sincerely': 2.0, u'ignore': -1.0, u'distrust': -3.0, u'imposes': -1.0, u'provoking': -1.0,
                 u'vibrant': 3.0, u'popular': 3.0, u'mediocrity': -3.0, u'foolish': -2.0, u'disorder': -2.0,
                 u'humorous': 2.0, u'goddamn': -3.0, u'unloved': -2.0, u'disinclined': -2.0, u'urgent': -1.0,
                 u'strongest': 2.0, u'loser': -3.0, u'selfishness': -3.0, u'curious': 1.0, u'irresistible': 2.0,
                 u'prosecutes': -1.0, u'collapses': -2.0, u'visioning': 1.0, u'warnings': -3.0, u'thrilled': 5.0,
                 u'stingy': -2.0, u'prosecuted': -2.0, u'innovation': 1.0, u'apathetic': -3.0, u'jumpy': -1.0,
                 u'swiftly': 2.0, u'hypocritical': -2.0, u'agreement': 1.0, u'refused': -2.0, u'looming': -1.0,
                 u'ache': -2.0, u'intense': 1.0, u'unconfirmed': -1.0, u'faith': 1.0, u'cautious': -1.0,
                 u'discontented': -2.0, u'exaggerated': -2.0, u'firing': -2.0, u'stricken': -2.0, u'greets': 1.0,
                 u'hahahah': 3.0, u'block': -1.0, u'exaggerates': -2.0, u'abusive': -3.0, u'nonsense': -2.0,
                 u'awaited': -1.0, u'piteous': -2.0, u'colliding': -1.0, u'risk': -2.0, u'calming': 2.0,
                 u'impressed': 3.0, u'infuriating': -2.0, u'sneaky': -1.0, u'infected': -2.0, u'grave': -2.0,
                 u'impresses': 3.0, u'bored': -2.0, u'insensitivity': -2.0, u'invite': 1.0, u'collapsed': -2.0,
                 u'audacious': 3.0, u'undeserving': -2.0, u'delighting': 3.0, u'alive': 1.0, u'hopes': 2.0,
                 u'dull': -2.0, u'gallantry': 3.0, u'redeemed': 2.0, u'exploration': 1.0, u'mature': 2.0,
                 u'highlight': 2.0, u'validates': 1.0, u'wicked': -2.0, u'repulse': -1.0, u'genial': 3.0,
                 u'devastating': -2.0, u'haunt': -1.0, u'warning': -3.0, u'denying': -2.0, u'disappoints': -2.0,
                 u'rainy': -1.0, u'sullen': -2.0, u'paradox': -1.0, u'peace': 2.0, u'backs': 1.0, u'tard': -2.0,
                 u'preventing': -1.0, u'tits': -2.0, u'unequaled': 2.0, u'mock': -2.0, u'nice': 3.0, u'smiles': 2.0,
                 u'scapegoat': -2.0, u'energetic': 2.0, u'accidental': -2.0, u'scandals': -3.0, u'problems': -2.0,
                 u'resign': -1.0, u'prepared': 1.0, u'helping': 2.0, u'drag': -1.0, u'smiled': 2.0, u'worsened': -3.0,
                 u'suffers': -2.0, u'downcast': -2.0, u'rescued': 2.0, u'humiliated': -3.0, u'attacking': -1.0,
                 u'impatient': -2.0, u'bribe': -3.0, u'ignorant': -2.0, u'menace': -2.0, u'avoid': -1.0,
                 u'discards': -1.0, u'rants': -3.0, u'cheerful': 2.0, u'infatuation': 2.0, u'intricate': 2.0,
                 u'screwed up': -3.0, u'spamming': -2.0, u'suave': 2.0, u'expelling': -2.0, u'obstinate': -2.0,
                 u'helps': 2.0, u'excluded': -2.0, u'stable': 2.0, u'dislike': -2.0, u'friendly': 2.0,
                 u'enslaves': -2.0, u'chagrined': -2.0, u'murderous': -3.0, u'torture': -4.0, u'slickest': 2.0,
                 u'asset': 2.0, u'manipulated': -1.0, u'accuse': -2.0, u'abduction': -2.0, u'cover-up': -3.0,
                 u'compassionate': 2.0, u'anxious': -2.0, u'verdict': -1.0, u'jerk': -3.0, u'comforts': 2.0,
                 u'unsatisfied': -2.0, u'calmed': 2.0, u'chastise': -3.0, u'uncomfortable': -2.0, u'exuberant': 4.0,
                 u'ardent': 1.0, u'manipulating': -1.0, u'odd': -2.0, u'mischiefs': -1.0, u'appeased': 2.0,
                 u'appeases': 2.0, u'melancholy': -2.0, u'upsetting': -2.0, u'misgiving': -2.0, u'desired': 2.0,
                 u'focused': 2.0, u'sexy': 3.0, u'enterprising': 1.0, u'irritating': -3.0, u'great': 3.0,
                 u'engage': 1.0, u'survivor': 2.0, u'uneasy': -2.0, u'distressed': -2.0, u'haunts': -1.0,
                 u'fuked': -4.0, u'honor': 2.0, u'distresses': -2.0, u'panicked': -3.0, u'danger': -2.0, u'win': 4.0,
                 u'terrified': -3.0, u'apprehensive': -2.0, u'crazy': -2.0, u'offends': -2.0, u'hardy': 2.0,
                 u'scandal': -3.0, u'droopy': -2.0, u'confidence': 2.0, u'cheered': 2.0, u'crap': -3.0,
                 u'illegal': -3.0, u'doubt': -1.0, u'weeping': -2.0, u'bitterly': -2.0, u'agreeable': 2.0,
                 u'noisy': -1.0, u'clever': 2.0, u'rich': 2.0, u'impress': 3.0, u'charming': 3.0, u'sore': -1.0,
                 u'unbelieving': -1.0, u'ashamed': -2.0, u'disabling': -1.0, u'duped': -2.0, u'annoy': -2.0,
                 u'challenge': -1.0, u'critic': -2.0, u'benefitting': 2.0, u'walkout': -2.0, u'recession': -2.0,
                 u'praise': 3.0, u'fulfill': 2.0, u'violence': -3.0, u'admires': 3.0, u'escapes': -1.0,
                 u'effectively': 2.0, u'wowww': 4.0, u'contempt': -2.0, u'hesitate': -2.0, u'united': 1.0,
                 u'daring': 2.0, u'despairs': -3.0, u'destroying': -3.0, u'buoyant': 2.0, u'rejoicing': 4.0,
                 u'struggles': -2.0, u'humerous': 3.0, u'fortunate': 2.0, u'delay': -1.0, u'fearsome': -2.0,
                 u'justifiably': 2.0, u'struggled': -2.0, u'comedy': 1.0, u'intelligent': 2.0, u'tension': -1.0,
                 u'blocks': -1.0, u'incompetence': -2.0, u'await': -1.0, u'bothered': -2.0, u'perjury': -3.0,
                 u'abuse': -3.0, u'fatigue': -2.0, u'solidarity': 2.0, u'criticized': -2.0, u'dont like': -2.0,
                 u'lame': -2.0, u'interrupted': -2.0, u'trembling': -2.0, u'acquitted': 2.0, u'prays': 1.0,
                 u'allow': 1.0, u'classy': 3.0, u'furious': -3.0, u'beauties': 3.0, u'widowed': -1.0, u'doubtful': -1.0,
                 u'nasty': -3.0, u'boosts': 1.0, u'perfect': 3.0, u'superior': 2.0, u'exclusion': -1.0, u'glee': 3.0,
                 u'winning': 4.0, u'revives': 2.0, u'stalled': -2.0, u'criminal': -3.0, u'violating': -2.0,
                 u'crash': -2.0, u'greater': 3.0, u'commended': 2.0, u'cutting': -1.0, u'twat': -5.0, u'kiss': 2.0,
                 u'terrible': -3.0, u'admonished': -2.0, u'panic': -3.0, u'mirthful': 3.0, u'expels': -2.0,
                 u'trap': -1.0, u'incapacitated': -2.0, u'disregard': -2.0, u'promise': 1.0, u'cry': -1.0,
                 u'thwart': -2.0, u'aggravates': -2.0, u'aggravated': -2.0, u'burdened': -2.0, u'incensed': -2.0,
                 u'enraging': -2.0, u'blesses': 2.0, u'gallant': 3.0, u'chaos': -2.0, u'fascist': -2.0,
                 u'hilarious': 2.0, u'postpone': -1.0, u'supports': 2.0, u'despairing': -3.0, u'jackasses': -4.0,
                 u'shortage': -2.0, u'greedy': -2.0, u'loomed': -1.0, u'conflicts': -2.0, u'embarrass': -2.0,
                 u'shrew': -4.0, u'scary': -2.0, u'hostile': -2.0, u'steal': -2.0, u'keen': 1.0, u'sleeplessness': -2.0,
                 u'sorrowful': -2.0, u'scare': -2.0, u'distracted': -2.0, u'embarrasses': -2.0, u'pitied': -1.0,
                 u'confuse': -2.0, u'reaches': 1.0, u'jesus': 1.0, u'embarrassed': -2.0, u'mocks': -2.0, u'bitch': -5.0,
                 u'lagging': -2.0, u'foreclosures': -2.0, u'reached': 1.0, u'suck': -3.0, u'unapproved': -2.0,
                 u'salient': 1.0, u'sadly': -2.0, u'cynical': -2.0, u'fuckers': -4.0, u'silencing': -1.0,
                 u'attack': -1.0, u'exhilarating': 3.0, u'perfectly': 3.0, u'misinformed': -2.0, u'adopts': 1.0,
                 u'interests': 1.0, u'craziest': -2.0, u'chagrin': -2.0, u'punish': -2.0, u'doomed': -2.0,
                 u'apologise': -1.0, u'dreary': -2.0, u'innovate': 1.0, u'depressing': -2.0, u'applauds': 2.0,
                 u'manipulation': -1.0, u'astounded': 3.0, u'loved': 3.0, u'glamorous': 3.0, u'warfare': -2.0,
                 u'boring': -3.0, u'bother': -2.0, u'tortured': -4.0, u'swindles': -3.0, u'tortures': -4.0,
                 u'pretends': -1.0, u'misunderstand': -2.0, u'accusing': -2.0, u'thwarted': -2.0, u'woebegone': -2.0,
                 u'poisons': -2.0, u'comfortable': 2.0, u'recommends': 2.0, u'sincerity': 2.0, u'miserable': -3.0,
                 u'blockbuster': 3.0, u'demonstration': -1.0, u'clearly': 1.0, u'bastard': -5.0, u'afraid': -2.0,
                 u'congrats': 2.0, u'boastful': -2.0, u'battles': -1.0, u'provokes': -1.0, u'skeptics': -2.0,
                 u'provoked': -1.0, u'asshole': -4.0, u'underestimating': -1.0, u'snubs': -2.0, u'alienation': -2.0,
                 u'clash': -2.0, u'prblm': -2.0, u'disappointments': -2.0, u'harmful': -2.0, u'courtesy': 2.0,
                 u'prisoner': -2.0, u'alarmed': -2.0, u'medal': 3.0, u'fervent': 2.0, u'fair': 2.0, u'deny': -2.0,
                 u'enthusiastic': 3.0, u'stronger': 2.0, u'fiasco': -3.0, u'contemptuous': -2.0, u'survived': 2.0,
                 u'exclusive': 2.0, u'chances': 2.0, u'sceptical': -2.0, u'agreed': 1.0, u'supported': 2.0,
                 u'beatific': 3.0, u'fear': -2.0, u'darkest': -2.0, u'agrees': 1.0, u'litigation': -1.0,
                 u'inspiring': 3.0, u'conciliate': 2.0, u'winner': 4.0, u'hopeful': 2.0, u'rash': -2.0, u'won': 3.0,
                 u'fatiguing': -2.0, u'inferior': -2.0, u'indignant': -2.0, u'prosecute': -1.0, u'doubting': -1.0,
                 u'harmed': -2.0, u'lucky': 3.0, u'exultant': 3.0, u'dodgy': -2.0, u'marvels': 3.0, u'spammers': -3.0,
                 u'gray': -1.0, u'worse': -3.0, u'deceives': -3.0, u'shy': -1.0, u'dejected': -2.0, u'wish': 1.0,
                 u'thoughtless': -2.0, u'deceived': -3.0, u'strengthened': 2.0, u'accuses': -2.0, u'humiliation': -3.0,
                 u'expel': -2.0, u'catastrophic': -4.0, u'yearning': 1.0, u'accused': -2.0, u'triumphant': 4.0,
                 u'desperate': -3.0, u'zealot': -2.0, u'awaits': -1.0, u'exploited': -2.0, u'wealth': 3.0,
                 u'insulting': -2.0, u'cheaters': -3.0, u'invulnerable': 2.0, u'frustrates': -2.0,
                 u'green washing': -3.0, u'favor': 2.0, u'beautify': 3.0, u'injustice': -2.0, u'horrible': -3.0,
                 u'progress': 2.0, u'harsher': -2.0, u'frustrated': -2.0, u'subversive': -2.0, u'fed up': -3.0,
                 u'ability': 2.0, u'importance': 2.0, u'joy': 3.0, u'sorrow': -2.0, u'regretful': -2.0, u'vitamin': 1.0,
                 u'embarrassment': -2.0, u'merry': 3.0, u'approval': 2.0, u'poorer': -2.0, u'lawsuit': -2.0,
                 u'absentee': -1.0, u'direful': -3.0, u'limits': -1.0, u'joke': 2.0, u'powerless': -2.0,
                 u'fulfilled': 2.0, u'admit': -1.0, u'deriding': -2.0, u'safely': 1.0, u'glorious': 2.0,
                 u'unclear': -1.0, u'commend': 2.0, u'competent': 2.0, u'laugh': 1.0, u'cynicism': -2.0,
                 u'validating': 1.0, u'pissed': -4.0, u'waste': -1.0, u'chastised': -3.0, u'perplexed': -2.0,
                 u'harshest': -2.0, u'interrupts': -2.0, u'spammer': -3.0, u'ensuring': 1.0, u'tense': -2.0,
                 u'chastises': -3.0, u'swindling': -3.0, u'piqued': -2.0, u'banish': -1.0, u'novel': 2.0,
                 u'toothless': -2.0, u'adores': 3.0, u'intimidate': -2.0, u'irate': -3.0, u'promotes': 1.0,
                 u'stunning': 4.0, u'hahaha': 3.0, u'promoted': 1.0, u'frustrating': -2.0, u'loathes': -3.0,
                 u'agonized': -3.0, u'chaotic': -2.0, u'unintelligent': -2.0, u'encouragement': 2.0, u'respected': 2.0,
                 u'optimistic': 2.0, u'agonizes': -3.0, u'whore': -4.0, u'lunatic': -3.0, u'unbiased': 2.0,
                 u'maddening': -3.0, u'defiant': -1.0, u'romance': 2.0, u'strange': -1.0, u'smarter': 2.0,
                 u'privileged': 2.0, u'difficult': -1.0, u'injured': -2.0, u'conflicting': -2.0, u'spiritless': -2.0,
                 u'overselling': -2.0, u'retarded': -2.0, u'fucker': -4.0, u'bullying': -2.0, u'discredited': -2.0,
                 u'discouraged': -2.0, u'fucked': -4.0, u'skepticism': -2.0, u'lobby': -2.0, u'expand': 1.0,
                 u'destruction': -3.0, u'retard': -2.0, u'frikin': -2.0, u'discounted': -1.0, u'fascinate': 3.0,
                 u'obstacles': -2.0, u'disoriented': -2.0, u'enrage': -2.0, u'failures': -2.0, u'drowns': -2.0,
                 u'restore': 1.0, u'stout': 2.0, u'cried': -2.0, u'discord': -2.0, u'mumpish': -2.0,
                 u'misbehaves': -2.0, u'mistaken': -2.0, u'cries': -2.0, u'glum': -2.0, u'misbehaved': -2.0,
                 u'happiness': 3.0, u'afflicted': -1.0, u'generous': 2.0, u'terrorized': -3.0, u'passively': -1.0,
                 u'killed': -3.0, u'arrest': -2.0, u'extends': 1.0, u'roflcopter': 4.0, u'exempt': -1.0,
                 u'despondent': -3.0, u'indignation': -2.0, u'smart': 1.0, u'clouded': -1.0, u'resolved': 2.0,
                 u'increased': 1.0, u'myth': -1.0, u'crushed': -2.0, u'virulent': -2.0, u'livid': -2.0,
                 u'mirthfully': 3.0, u'burden': -2.0, u'resolves': 2.0, u'crushes': -1.0, u'woeful': -3.0,
                 u'prominent': 2.0, u'loss': -3.0, u'racists': -3.0, u'helpful': 2.0, u'inviting': 1.0,
                 u'inquisitive': 2.0, u'exploiting': -2.0, u'admitted': -1.0, u'warned': -2.0, u'nerves': -1.0,
                 u'poor': -2.0, u'scared': -2.0, u'hail': 2.0, u'immortal': 2.0, u'growth': 2.0, u'supportive': 2.0,
                 u'neglecting': -2.0, u'leak': -1.0, u'corpse': -1.0, u'anguished': -3.0, u'rewarding': 2.0,
                 u'woohoo': 3.0, u'screwed': -2.0, u'worsen': -3.0, u'blurry': -2.0, u'benefitted': 2.0,
                 u'murderer': -2.0, u'reaching': 1.0, u'hooligan': -2.0, u'chokes': -2.0, u'slut': -5.0,
                 u'pressure': -1.0, u'uptight': -2.0, u'worthy': 2.0, u'scapegoats': -2.0, u'choked': -2.0,
                 u'frustrate': -2.0, u'hiding': -1.0, u'gained': 2.0, u'inconsiderate': -2.0, u'visions': 1.0,
                 u'freedom': 2.0, u'swear': -2.0, u'discard': -1.0, u'contending': -1.0, u'obliterated': -2.0,
                 u'commitment': 2.0, u'screamed': -2.0, u'na\xefve': -2.0, u'badass': -3.0, u'godsend': 4.0,
                 u'rejoice': 4.0, u'lagged': -2.0, u'indoctrinates': -2.0, u'awarded': 3.0, u'stamina': 2.0,
                 u'restricts': -2.0, u'frustration': -2.0, u'indoctrinated': -2.0, u'relishing': 2.0, u'touted': -2.0,
                 u'abductions': -2.0, u'bitches': -5.0, u'not good': -2.0, u'blaming': -2.0, u'admonish': -2.0,
                 u'fuckhead': -4.0, u'gain': 2.0, u'contemptuously': -2.0, u'ha': 2.0, u'assets': 2.0, u'lovely': 3.0,
                 u'glory': 2.0, u'protesting': -2.0, u'distract': -2.0, u'warmth': 2.0, u'excitement': 3.0,
                 u'cruel': -3.0, u'convince': 1.0, u'delights': 3.0, u'gagged': -2.0, u'gullibility': -2.0,
                 u'faggot': -3.0, u'strengthens': 2.0, u'horrific': -3.0, u'intimidating': -2.0, u'inadequate': -2.0,
                 u'meaningless': -2.0, u'upsets': -2.0, u'goodness': 3.0, u'authority': 1.0, u'infatuated': 2.0,
                 u'immobilized': -1.0, u'detain': -2.0, u'sick': -2.0, u'gallantly': 3.0, u'reckless': -2.0,
                 u'derails': -2.0, u'profiteer': -2.0, u'ecstatic': 4.0, u'traumatic': -3.0, u'treason': -3.0,
                 u'astounding': 3.0, u'insults': -2.0, u'chance': 2.0, u'stab': -2.0, u'animosity': -2.0,
                 u'acquits': 2.0, u'inspiration': 2.0, u'ghost': -1.0, u'insipid': -2.0, u'bereaves': -2.0,
                 u'jewel': 1.0, u'disconsolation': -2.0, u'accidents': -2.0, u'expands': 1.0, u'abhor': -3.0,
                 u'bereaved': -2.0}


    return scores


def tweet_list(twitterData):
    tweetlist = []

    tweetlist.append(twitterData)
    return tweetlist


def sentimentAnalysis(data):
    tweet = json.loads(data)
    if 'text' in tweet:
        tweet_text = tweet['text']
        tweet_processed = cleanTweet(tweet_text)
        sentiments = sentiment_list()
        tweets = tweet_list(tweet_processed)
        # print tweets
        sent_score = 0
        for index in range(len(tweets)):
            tweet_word = tweets[index].split()
            for word in tweet_word:
                if not (word.encode('utf-8', 'ignore') == ""):
                    if word in sentiments.keys():
                        sent_score = sent_score + float(sentiments[word])
                    else:
                        sent_score = sent_score
        print(sent_score)
        return sent_score, tweet_text
